### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by poVoq** [sedenion/xows#4]
This looked really promising. Did you abandon this project?

**Comment by sedenion** [comment]
Not really abandoned, but some trouble to find motivation... I need sense/meaning to what I do and, at a time everybody use big social platforms trough dedicated applications on smartphones or tablets with encrypted data and "cloud" everywhere, I feel being a dinosaur developing application for outdated computers and a dying Internet paradigm.

**Comment by Echolon** [comment]
> Not really abandoned, but some trouble to find motivation... I need sense/meaning to what I do and, at a time everybody use big social platforms trough dedicated applications on smartphones or tablets with encrypted data and "cloud" everywhere, I feel being a dinosaur developing application for outdated computers and a dying Internet paradigm.

Sad to hear, I hope you can still find motivation.

**Comment by poVoq** [comment]
Nice to see some activity again 👍

**Comment by fishnibble** [comment]
I'd love to help out. What needs to be done?

**Comment by sedenion** [comment]
What need to be done before a next release (this is goal I fixed to myself) are MUC administration and moderation features and user password change feature (to be accessed via user profil edit page). Each require creation of functionality throut multiple software layer, from the front-end theme (HTML part) to the XMPP protocol part... Not easy if you discover the software. 
I don't think I can delegate the MUC part, too complexe and involve too many design choices and rewrite at once. May be you can try to implement password changes mechanism, which should not require much code addition. 

Another thing I was thinking about is enhencement of Avatar upload, by adding some edition features to allow user to slide and crop the wanted part of the image to set it as avatar. I would like to implement this without Canvas if possible, to stay lightwheight, but I don't know if such thing is possible.

**Comment by poVoq** [comment]
Very nice to see so much activity again 👍

**Comment by sjehuda** [comment]
> Not really abandoned, but some trouble to find motivation... I need sense/meaning to what I do and, at a time everybody use big social platforms trough dedicated applications on smartphones or tablets with encrypted data and "cloud" everywhere, I feel being a dinosaur developing application for outdated computers and a dying Internet paradigm.

Once you have a usable software, which "just" works, and does what it stated to do, then there be no obstacle to you. Never.

Every year, and even every month, many people seek for software that they control, and XMPP provides your own system with both messaging and publishing capabilities.

Once it is easy for the family, you have people loyal to it.

Also, intelligence, police, governments and other "official" entities utilize XMPP, though most of them do not encourage XMPP because XMPP gives you control over your data.

Also, Movim is widely utilized by academic institutions over Europe, but it is not advertized, mostly because those institutions are not public for all, so Movim and XMPP are more popular than ActivityPub amongst academic institutions.

**Comment by sjehuda** [comment]
Also, Movim is widely utilized by academic institutions over Europe, but it is not advertized, mostly because those institutions are not public for all, so Movim and XMPP are more popular than ActivityPub amongst academic institutions.

**Comment by poVoq** [comment]
> Also, Movim is widely utilized by academic institutions over Europe, but it is not advertized, mostly because those institutions are not public for all, so Movim and XMPP are more popular than ActivityPub amongst academic institutions.

You have a source for this? First time I hear about that.

**Comment by sjehuda** [comment]
No. I do not have sources.

The only instance which was related to some universities and was accessible is this https://jabber.icb.at/

It seems to be out of order, yet it was usable a few months ago.

Other instances, are accessible via universities intranet.

There are two colleges here that I know for certain that utilize Movim, only internally.
